appName: TYWZOJ

server:
  hostname: 127.0.0.1
  port: 5050

database:
  hostname: 127.0.0.1
  port: 3306
  type: mariadb
  username: root
  password: "123456"
  database: tywzoj

redis: redis://127.0.0.1:6379

security:
  sessionSecret: # do not leak this secret

cdnUrl: https://cdn.tywzoj.example/
