appName: Algozia

server:
  hostname: 127.0.0.1
  port: 5050
  trustProxy:
    - loopback

database:
  hostname: 127.0.0.1
  port: 3306
  type: mariadb
  username: root
  password: "123456"
  database: algozia

minio:
  endPoint: 127.0.0.1
  port: 9000
  useSSL: false
  accessKey: access key
  secretKey: secret key
  pathStyle: true
  region: us-east-1
  bucket:
    name: algozia
    publicUrl: https://file.algozia.example/
  tempBucket:
    name: algozia-temp
    publicUrl: https://upload.algozia.example/

redis: redis://127.0.0.1:6379

security:
  sessionSecret: # do not leak this secret
  fileUploadSecret: # do not leak this secret

cdnUrl: https://cdn.algozia.example/

pagination:
  homePageRanklist: 10
  homePageArticle: 10
  problem: 50
  contest: 20
  homework: 20
  submission: 50
  ranklist: 20
  article: 20

judge:
  dynamicTaskPriority: true
  limit:
    compilerMessage: 524288
    outputSize: 104857600
    dataDisplay: 128
    dataDisplayForSubmitAnswer: 128
    stderrDisplay: 5120
