name: APP CI

on:
  push:
    branches: [main]
    paths: ["app/**"]
  pull_request:
    branches: [main]
    paths: ["app/**"]

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.0.0

      - name: Go to APP directory
        run: cd app

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build
