name: CDN CI

on:
  push:
    branches: [main]
    paths:
      - "cdn/**"
      - ".github/workflows/cdn-ci.yml"
  pull_request:
    branches: [main]
    paths:
      - "cdn/**"
      - ".github/workflows/cdn-ci.yml"

jobs:
  builds:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cdn
    steps:
      - name: Checkout
        uses: actions/checkout@v4.0.0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn bundle:prod
