name: CDN CI

on:
  pull_request:
    branches: [main]
    paths:
      - "cdn/**"
      - ".github/workflows/cdn-main-pr.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./cdn"
    steps:
      - name: Checkout
        uses: actions/checkout@v4.0.0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: "cdn/.nvmrc"

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn bundle:prod
